# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Verify Changed files
        uses: sfc-gh-skhire29/get-changed-files-action@v0.1     
        id: changed_files
      
      - name: Print head 
        run: echo "${{ github.head_ref }}"
        
      - name: Print target
        run: echo "${{ github.base_ref }}"
      
      - name: git diff
        run: |
          format_py=.py
          target=${{ github.base_ref }}
          head=${{ github.head_ref }}
          
          git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main | grep -E "${format_py}"
      
      
      
      - name: Print python changed files
        run: echo "${{ steps.changed_files.outputs.python_changed_files }}"
        
      - name: Print sql changed files
        run: echo "${{ steps.changed_files.outputs.sql_changed_files }}"  
        
