# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Verify Changed files
        uses: sfc-gh-skhire29/get-changed-files-action@v.237
        id: changed_files
      
      - name: Print head 
        run: echo "${{ github.head_ref }}"
        
      - name: Print target
        run: echo "${{ github.base_ref }}"
      
      - name: git diff
        run: |
          format_py=.py
          target=${{ github.base_ref }}
          head=${{ github.head_ref }}
          git fetch origin main:main
          git fetch origin $head:$head
          git diff --name-only $head main
      
      
      - name: Print python changed files
        run: echo "${{ steps.changed_files.outputs.python_changed_files }}"
        
      - name: Print sql changed files
        run: echo "${{ steps.changed_files.outputs.sql_changed_files }}"  
       
        if: ${{ steps.changed_files.outputs.sql_changed_files == '' }}
      - name: Check sql changed or not
        run: echo "Sql null"
      
        if: ${{ steps.changed_files.outputs.python_changed_files != '' }}
      - uses: sfc-gh-skhire29/python-lint-action-1@v1.2
        with:
            python-root-list: "${{ steps.changed_files.outputs.python_changed_files }}"
            use-pylint: true
            use-pycodestyle: false
            use-flake8: false
            use-black: false
            extra-pylint-options: "-sn"
